export const data = {
  personal: {
    name: "Prahlad Puspa Regmi",
    shortName: "Prahlad Regmi",
    titles: ["Computer Science Student", "Full Stack Developer", "Future Software Engineer"],
    university: "Youngstown State University",
    degree: "B.S. Computer Science – Minor: Mathematics",
    gpa: "3.56",
    graduation: "Dec 2026",
    location: "Youngstown, OH",
    email: "pregmi02@student.ysu.edu",
    phone: "+1 (330) 883-2706",
    linkedin: "https://www.linkedin.com/in/prahlad-puspa-regmi-356301260",
    github: "https://github.com/prah-lad",
    resume: "./Prahlad_Resume.pdf",
    about: "Computer Science undergraduate at Youngstown State University with a minor in Mathematics, graduating December 2026. Passionate about building data-driven systems, REST APIs, and IoT infrastructure that solve real-world problems. Experience spanning ISP data operations in Nepal to university tech support in Ohio.",
  },
  skills: ["Python", "JavaScript", "TypeScript", "C++", "Java", "SQL", "Flask", "REST APIs", "React", "Next.js", "Node.js", "Git", "Pandas", "NumPy", "Excel", "ESP32"],
  experience: [
    {
      id: "CORE_01",
      title: "Instructional Technology Assistant",
      org: "Youngstown State University",
      location: "Youngstown, OH",
      period: "Aug 2023 – Aug 2024",
      color: "#00FF88",
      bullets: [
        "Technical support for LMS tools used by 10,000+ campus community members",
        "Maintained and organized digital course materials for faculty",
        "Assisted instructors with technology integration and workflow documentation",
      ],
    },
    {
      id: "CORE_02",
      title: "Data Assistant – Network Services",
      org: "Classic Tech ISP",
      location: "Nepal",
      period: "Jul 2020 – Nov 2022",
      color: "#00C8FF",
      bullets: [
        "Analyzed operational datasets tracking service quality & customer trends",
        "Built Excel reporting pipelines with PivotTables and advanced formulas",
        "Performed data cleaning across large customer record databases",
        "Produced weekly KPI reports used by management for strategic planning",
      ],
    },
    {
      id: "CORE_03",
      title: "Mathematics Tutor",
      org: "Hetauda School of Management",
      location: "Nepal",
      period: "Jan 2019 – May 2020",
      color: "#FFB347",
      bullets: [
        "Individual and group tutoring in calculus and statistics",
        "Tracked student progress and designed custom practice assessments",
      ],
    },
    {
      id: "CORE_04",
      title: "B.S. Computer Science",
      org: "Youngstown State University",
      location: "Youngstown, OH",
      period: "Expected Dec 2026",
      color: "#a855f7",
      bullets: [
        "GPA: 3.56/4.0 – Dean's List",
        "Minor: Mathematics",
        "Predictive Modeling, Database Dev, Data Structures, Software Engineering",
        "Linear Algebra, Probability & Statistics, Algorithms",
      ],
    },
  ],
  projects: [
    {
      id: "MOD_01",
      title: "APEX Trading Agent",
      category: "AI · Autonomous · Live Markets",
      description: "Autonomous crypto trading agent powered by Claude AI. Analyzes live Hyperliquid perpetuals market data and makes real-time BUY/SELL decisions with confidence scores, stop loss, and take profit targets.",
      stack: ["Next.js", "TypeScript", "Claude AI", "Supabase", "Hyperliquid API", "Tailwind"],
      github: "https://github.com/prah-lad/apex-trading-agent",
      demo: "",
      featured: true,
      status: "LIVE",
    },
    {
      id: "MOD_02",
      title: "LotOwl – Smart Parking",
      category: "IoT · Backend · Full-Stack",
      description: "HackYSU 2026 – 24hr hackathon. Real-time parking availability using HC-SR04 ultrasonic sensors on ESP32 microcontrollers, Flask REST API, and interactive Leaflet.js campus map.",
      stack: ["Python", "Flask", "REST API", "ESP32", "HC-SR04", "Leaflet.js"],
      github: "https://github.com/bananaPeppers/lotowl",
      demo: "",
      featured: true,
      status: "COMPLETE",
    },
    {
      id: "MOD_03",
      title: "Laboro",
      category: "Full-Stack · SaaS",
      description: "Labor marketplace platform connecting workers with employers. Full-stack SaaS with authentication, job matching, and real-time notifications.",
      stack: ["React", "Node.js", "PostgreSQL", "TypeScript"],
      github: "https://github.com/prah-lad/laboro",
      demo: "",
      featured: false,
      status: "IN_DEV",
    },
    {
      id: "MOD_04",
      title: "Equity Engine",
      category: "Finance · AI",
      description: "AI-powered equity analysis platform with real-time market data integration, stock screening, and portfolio analytics dashboard.",
      stack: ["Python", "Flask", "React", "Financial APIs"],
      github: "https://github.com/prah-lad/equity-engine",
      demo: "",
      featured: false,
      status: "COMPLETE",
    },
    {
      id: "MOD_05",
      title: "Stock Market Analyzer",
      category: "Data Analysis · C++",
      description: "C++ tool processing historical price data to identify directional trends using efficient data structures. Calculates moving averages and signals momentum.",
      stack: ["C++", "Data Structures", "Algorithms"],
      github: "https://github.com/prah-lad/stock-analyzer",
      demo: "",
      featured: false,
      status: "COMPLETE",
    },
    {
      id: "MOD_06",
      title: "Path Finder",
      category: "Algorithms · C++",
      description: "C++ pathfinding tool implementing Dijkstra's and A* to compute shortest routes in grid datasets. Benchmarks algorithm efficiency side by side.",
      stack: ["C++", "Dijkstra's", "A* Algorithm"],
      github: "https://github.com/prah-lad/path-finder",
      demo: "",
      featured: false,
      status: "COMPLETE",
    },
  ],
  awards: [
    {
      id: "ALU_01",
      title: "HackYSU 2026 — LotOwl",
      org: "Youngstown State University Hackathon",
      desc: "Built full-stack IoT smart parking system in 24 hours with a 3-person team. Designed entire Flask REST backend and API architecture from scratch.",
      opcode: "0x01",
      result: "SUCCESS",
    },
    {
      id: "ALU_02",
      title: "Dean's List",
      org: "Youngstown State University",
      desc: "Academic excellence recognition — 3.56/4.0 GPA in Computer Science with Mathematics minor. Consistent honor roll across multiple semesters.",
      opcode: "0x02",
      result: "SUCCESS",
    },
    {
      id: "ALU_03",
      title: "Club President",
      org: "Hetauda Computer Club · Nepal · 2020–2022",
      desc: "Led computing community initiatives, organized workshops and hackathons, managed cross-functional teams across Makawanpur, Nepal.",
      opcode: "0x03",
      result: "SUCCESS",
    },
    {
      id: "ALU_04",
      title: "Continuous Learning",
      org: "Kaggle · SQLBolt · Tableau · Excel",
      desc: "Kaggle Learn (Pandas, Data Cleaning) · SQLBolt & Mode SQL · Tableau Public Dashboards · Advanced Excel (PivotTables, Lookups, Reporting).",
      opcode: "0x04",
      result: "IN_PROGRESS",
    },
  ],
  registers: [
    { id: "R1", label: "Email", value: "pregmi02@student.ysu.edu", href: "mailto:pregmi02@student.ysu.edu", type: "mail" },
    { id: "R2", label: "LinkedIn", value: "/in/prahlad-puspa-regmi", href: "https://www.linkedin.com/in/prahlad-puspa-regmi-356301260", type: "link" },
    { id: "R3", label: "GitHub", value: "github.com/prah-lad", href: "https://github.com/prah-lad", type: "link" },
    { id: "R4", label: "Resume", value: "Prahlad_Resume.pdf", href: "./Prahlad_Resume.pdf", type: "download" },
  ],
};
